export * from './svg-circle-gain/svg-circle-gain.component';
export * from './svg-gain/svg-gain.component';
export * from './svg-question/svg-question.component';
export * from './svg-losange/svg-losange.component';
export * from "./svg-joker-fifty/svg-joker-fifty.component";
export * from "./svg-joker-call/svg-joker-call.component";
export * from "./svg-joker-public/svg-joker-public.component";
export * from "./svg-euro/svg-euro.component";
export * from "./svg-home/svg-home.component";